### ISSUE TITLE
Il faudrait vérifier l'OS

### ISSUE THREAD

**Issue by MichelBaie** [FoobarIT/nodar#1]
NodeJS sur ubuntu 18.04 dans leur dépots est totalement obsolète.
Il faudrait proposer la version de NodeJS à installer et ajouter le repo officiel en fonction de l'os.

**Comment by FoobarIT** [comment]
Bonjour @MichelBaie, est-ce un problème que vous avez rencontrez ?

**Comment by MichelBaie** [comment]
Une simple suggestion :)
